### ISSUE TITLE
Towny Overrides other plugins DIsplayName()

### ISSUE THREAD

**Issue by mixxit** [Zren/Towny#4]
Causing plugins like DIspNameChanger to fail

**Comment by Zren** [comment]
Croxis already changed that:
https://github.com/croxis/Towny
https://github.com/croxis/Towny/blob/master/src/ca/xshade/bukkit/towny/event/TownyPlayerLowListener.java

It's a low listener, so it's parsed before or after normal (I forget). I used to have it so it modified the entire format of chat.

**Comment by mixxit** [comment]
also changing modify_chat_names = false seems to fix it
